<?php


/**
 * Implements hook_theme().
 */
function lb_repeat_schedules_theme() {
  return [
    'block__inline_block__lb_repeat_schedules' => [
      'base hook' => 'block',
      'template' => 'block--inline-block--lb-repeat-schedules',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lb_repeat_schedules_preprocess_block__inline_block__lb_repeat_schedules(&$variables) {
  if ($variables['in_preview']) {
    $variables['in_preview_placeholder'] = t('Repeat Schedules: To see your changes in this block, please save the layout.');
  }
}
