<?php

/**
 * @file
 * Repeat Schedules Filter by Instructor module file.
 */

use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function repeat_schedules_instructor_preprocess_block(&$variables) {
  switch ($variables['plugin_id']) {

    case 'inline_block:lb_repeat_schedules':
      $variables['#attached']['library'][] =
        'repeat_schedules_instructor/repeat-schedules-instructor';

      break;
  }
}

/**
 * Implements hook_preprocess_ENTITY_TYPE().
 */
function repeat_schedules_instructor_preprocess_paragraph(array &$variables) {
  $elements = $variables['elements'] ?? [];
  $paragraph = $elements['#paragraph'] ?? '';
  if (($paragraph instanceof ParagraphInterface) && ($paragraph->bundle() != 'repeat_schedules')) {
    return;
  }
  if (($paragraph instanceof ParagraphInterface) && ($paragraph->bundle() === 'repeat_schedules')) {
    $variables['#attached']['library'][] = 'repeat_schedules_instructor/repeat-schedules-instructor';
  }
}
